#!/bin/bash

_output_stdout_dir="output-stdout"
_output_stderr_dir="output-stderr"

_jar_dir="jar"
_conf_dir="$1"

for _filename_full in $_conf_dir/*
do
	
	(/opt/spark-2.1/bin/spark-submit \
	  --jars $_jar_dir/config-1.3.1.jar,$_jar_dir/scallop_2.11-2.1.1.jar,$_jar_dir/spark-measure_2.11-0.1-SNAPSHOT.jar\
	  --class "ConsistencyCheckApp" $_jar_dir/machine-learning_2.11-1.0.jar\
	  --config $_filename_full | \
	    tee -a $_output_stdout_dir/check-$_conf_dir-stdout.log) 
done
