#!/bin/bash

export HADOOP_CONF_DIR=/etc/hadoop/conf
export YARN_CONF_DIR=$HADOOP_CONF_DIR

_now=$(date +"%Y-%m-%d_%H-%M-%S")
_output_stderr_dir="output-yarn-stderr"
_output_stdout_dir="output-yarn-stdout"
_jar_dir="jar"
_conf_dir="conf-single"

(/opt/spark-2.1/bin/spark-submit \
  --jars $_jar_dir/config-1.3.1.jar,$_jar_dir/scallop_2.11-2.1.1.jar,$_jar_dir/spark-measure_2.11-0.1-SNAPSHOT.jar \
  --properties-file spark-submit-yarn.conf \
  --class "GenreLogRegCrossValidateApp" $_jar_dir/machine-learning_2.11-1.0.jar \
  --config $_conf_dir/genre-logisticRegressionCrossValidate.conf | \
    tee $_output_stdout_dir/$_now-stdout.log) 3>&1 1>&2 2>&3 | \
    tee $_output_stderr_dir/$_now-stderr.log 
  
